ifneq ($(filter m y,$(CONFIG_CHIPONE_ESD)),)
ccflags-y += -DCONFIG_CTS_ESD_PROTECTION
endif

ifneq ($(filter m y,$(CONFIG_INPUT_CHIPONE_0FLASH_MMI_ENABLE_DOUBLE_TAP)),)
	ccflags-y += -DCHIPONE_SENSOR_EN
endif

ifneq ($(filter m y,$(CONFIG_INPUT_CHIPONE_0FLASH_MMI_NOTIFY_TOUCH_STATE)),)
	ccflags-y += -DCHIPONE_SET_TOUCH_STATE
endif

ifneq ($(filter m y,$(CONFIG_INPUT_CHIPONE_PANEL_NOTIFICATIONS)),)
ccflags-y += -DCHIPONE_CONFIG_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_GTP_LAST_TIME)),)
	ccflags-y += -DCONFIG_GTP_LAST_TIME
endif

ifneq ($(filter m y, $(CONFIG_BOARD_USES_DOUBLE_TAP_CTRL)),)
	ccflags-y += -DCONFIG_BOARD_USES_DOUBLE_TAP_CTRL
endif

ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_MMI)),)
	ccflags-y += -DCONFIG_INPUT_TOUCHSCREEN_MMI
endif

ifeq ($(TARGET_BUILD_VARIANT),user)
	ccflags-y += -DCFG_CTS_FOR_GKI
endif

ifneq ($(filter m y, $(CONFIG_STOWED_MODE_EN)),)
	ccflags-y += -DCTS_STOWED_MODE_EN
endif

ifneq ($(filter m y,$(TOUCHSCREEN_PM_BRL_SPI)),)
	ccflags-y += -DTOUCHSCREEN_PM_BRL_SPI
endif

ifneq ($(filter m y,$(CONFIG_CHIPONE_CHECK_DEVICE_BOOTMODE)),)
	ccflags-y += -DCTS_CHECK_DEVICE_BOOTMODE
endif

obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += chipone_tddi_v2_mmi.o

chipone_tddi_v2_mmi-objs := cts_driver.o
chipone_tddi_v2_mmi-objs += cts_core.o
chipone_tddi_v2_mmi-objs += cts_sfctrlv2.o
chipone_tddi_v2_mmi-objs += cts_spi_flash.o
chipone_tddi_v2_mmi-objs += cts_firmware.o
chipone_tddi_v2_mmi-objs += cts_test.o
chipone_tddi_v2_mmi-objs += cts_charger_detect.o
chipone_tddi_v2_mmi-objs += cts_earjack_detect.o
chipone_tddi_v2_mmi-objs += cts_tcs.o
chipone_tddi_v2_mmi-objs += cts_platform.o
chipone_tddi_v2_mmi-objs += cts_tool.o
chipone_tddi_v2_mmi-objs += cts_sysfs.o
chipone_tddi_v2_mmi-objs += cts_strerror.o
chipone_tddi_v2_mmi-objs += cts_oem.o
